.data  ; Segmento de datos
MODO DB ?
ERROR_2 DB 2


.code  ; Segmento de c�digo
MOV AX, 0x7000
MOV ES, AX
MOV AX, 0x3000
MOV SS, AX

PROCERSAR_COMANDO:
	IN AX, 20 ; Lee el PUERTO_ENTRADA
	
	CMP AX, 1
	JE TAG_CAMBIAR_MODO

	CMP AX, 255
	JE EXIT

    JMP PROCERSAR_COMANDO

TAG_CAMBIAR_MODO:
	CALL CAMBIAR_MODO

	JMP PROCERSAR_COMANDO	

CAMBIAR_MODO PROC
	PUSH AX
	PUSH BX

	MOV BX, 0

	IN AX, 20 ; MODO
		CMP AX, 0
		JE MODO_STATICO ; SE SETTEA EL MODO STATICO

		CMP AX, 1
		JE MODO_DINAMICO ; SE SETTEA EL MODO DINAMICO

	ERROR_CAMBIAR_MODO: ; IMPRIME ERROR 2: MODO NO RECONOCIDO
		MOV AX, [ERROR_2]
		OUT 22, AX
		JMP END_CAMBIAR_MODO

	MODO_STATICO:
		MOV byte ptr [MODO], 0
		JMP INI_CAMBIAR_MODO

	MODO_DINAMICO:
		MOV byte ptr [MODO], 1
		JMP INI_CAMBIAR_MODO
		
			
	INI_CAMBIAR_MODO: 
		MOV ES:[BX], 0x8000 ; WHILE IN MEMORIA RESERVADA -> BORRAR CONTENIDO
		ADD BX, 2
		CMP BX, 4096
		JNE INI_CAMBIAR_MODO

	END_CAMBIAR_MODO:
		POP BX
		POP AX
		RET
CAMBIAR_MODO ENDP


AGREGAR_NODO_STATIC PROC
	PUSH BP
	MOV BP, SP

	
	
	MOV DX, [BP + 6] ; VALOR QUE QUIERO AGREGAR
	MOV AX, [BP + 4] ; VALOR CON EL QUE QUIERO COMPARAR
	CMP DX, AX 

	JL S_IZQ
	JG S_DER
	JMP S_ERR

	S_IZQ:
		PUSH DX
		
		PUSH ES:

	S_DER:

	S_ERR:

	POP BP
	RET
AGREGAR_NODO_STATIC ENDP

LOG PROC
	OUT 22, AX
	RET
LOG ENDP

EXIT:

.ports ; Definici�n de puertos
20: 1, 0, 2, 25,  2, 15, 2, 7, 2, 18, 2, 20, 2, 40, 3, 4, 255 
; 200: 1,2,3  ; Ejemplo puerto simple
; 201:(100h,10),(200h,3),(?,4)  ; Ejemplo puerto PDDV

.interrupts ; Manejadores de interrupciones
; Ejemplo interrupcion del timer
;!INT 8 1
;  iret
;!ENDINT
